classdef Audiogram < handle
    properties (Access = private)
        mainFigure
        mainAxes
    end
    
    methods
        function self = Audiogram()
            mainFigure = figure( ...
                'menubar', 'none', ...
                'toolbar', 'none', ...
                'numbertitle', 'off', ...
                'units', 'normalized', ...
                'position', [0.05, 0.05, 0.84, 0.84], ...
                'name', 'Audiogram', ...
                'handlevisibility', 'off', ...
                'closerequestfcn', @(~, ~)self.onCloseRequest());
            mainAxes = axes( ...
                'units', 'normalized', ...
                'position', [0.1, 0.1, 0.8, 0.8], ...
                'Parent', mainFigure, ...
                'xgrid', 'on', ...
                'ygrid', 'on', ...
                'xlim', [0, 10000], ...
                'xtick', [250,500,750,1000,1500,2000,3000,4000,6000,8000], ...
                'buttondownfcn', @(~, ~)self.onAxesClick());
            self.mainFigure = mainFigure;
            self.mainAxes = mainAxes;
        end
    end
    
    methods (Access = private)
        function onCloseRequest(self)
            delete(self.mainFigure);
        end
        
        function onAxesClick(self)
        end
    end
end

